/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                  '#c6c6c8',
        'primary-dim':              '#b8b9bb',
        'primary-fixed':            '#e2e2e4',
        'primary-fixed-dim':        '#d4d4d6',
        'primary-container':        '#454749',
        'on-primary':               '#3f4042',
        'on-primary-fixed':         '#3e3f41',
        'on-primary-fixed-variant': '#5a5c5d',
        'on-primary-container':     '#d0d0d2',
        'inverse-primary':          '#5e5f61',
        'secondary':                '#a09d9d',
        'secondary-dim':            '#a09d9d',
        'secondary-fixed':          '#e5e2e1',
        'secondary-fixed-dim':      '#d7d4d3',
        'secondary-container':      '#3c3b3b',
        'on-secondary':             '#202020',
        'on-secondary-fixed':       '#403f3f',
        'on-secondary-fixed-variant': '#5c5b5b',
        'on-secondary-container':   '#c1bfbe',
        'tertiary':                 '#ffdd79',
        'tertiary-dim':             '#e6c047',
        'tertiary-fixed':           '#f5ce53',
        'tertiary-fixed-dim':       '#e6c047',
        'tertiary-container':       '#f5ce53',
        'on-tertiary':              '#624e00',
        'on-tertiary-fixed':        '#413200',
        'on-tertiary-fixed-variant': '#634e00',
        'on-tertiary-container':    '#584500',
        'surface':                  '#0e0e0e',
        'surface-dim':              '#0e0e0e',
        'surface-bright':           '#2c2c2c',
        'surface-tint':             '#c6c6c8',
        'surface-variant':          '#262626',
        'surface-container-lowest': '#000000',
        'surface-container-low':    '#131313',
        'surface-container':        '#1a1919',
        'surface-container-high':   '#202020',
        'surface-container-highest': '#262626',
        'on-surface':               '#e7e5e4',
        'on-surface-variant':       '#acabaa',
        'inverse-surface':          '#fcf8f8',
        'inverse-on-surface':       '#565554',
        'background':               '#0e0e0e',
        'on-background':            '#e7e5e4',
        'outline':                  '#767575',
        'outline-variant':          '#484848',
        'error':                    '#ee7d77',
        'error-dim':                '#bb5551',
        'error-container':          '#7f2927',
        'on-error':                 '#490106',
        'on-error-container':       '#ff9993',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        mono:     ['JetBrains Mono', 'Consolas', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      animation: {
        'pulse-slow':  'pulse 3s cubic-bezier(0.4,0,0.6,1) infinite',
        'marquee':     'marquee 20s linear infinite',
        'float':       'float 6s ease-in-out infinite',
        'orb-breathe': 'orbBreathe 4s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-8px)' },
        },
        orbBreathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%':      { transform: 'scale(1.04)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
